#!/usr/bin/env python3
"""BRIEF/PLAN reports 파생 뷰 자동 생성.

TASK-090 reports indexing 으로 도입. `agents/lead_engineer/reports/` 의 frontmatter
를 집계해 4종 파생 뷰를 생성한다.

Usage:
  python scripts/generate_report_views.py

출력 파일 (모두 자동 생성, 직접 수정 금지):
  agents/lead_engineer/reports/VIEW-by-kind.md
  agents/lead_engineer/reports/VIEW-by-decision-topic.md
  agents/lead_engineer/reports/VIEW-by-related-task.md
  agents/lead_engineer/reports/VIEW-by-tag.md

frontmatter 가 없는 파일(README, INDEX, VIEW-*)은 제외된다.
"""
from __future__ import annotations

import argparse
import datetime as _dt
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass

ROOT = Path(__file__).resolve().parents[1]
REPORTS_DIR = ROOT / "agents" / "lead_engineer" / "reports"


def parse_frontmatter(text: str) -> dict | None:
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---\n", 4)
    if end == -1:
        end = text.find("\n---", 4)
        if end == -1:
            return None
    body = text[4:end]
    result: dict = {}
    for line in body.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if ":" not in stripped:
            continue
        key, _, val = stripped.partition(":")
        key = key.strip()
        val = val.strip()
        if val.startswith("[") and val.endswith("]"):
            inner = val[1:-1].strip()
            if not inner:
                result[key] = []
            else:
                items = [s.strip().strip("'\"") for s in inner.split(",") if s.strip()]
                result[key] = items
        elif (val.startswith('"') and val.endswith('"')) or (val.startswith("'") and val.endswith("'")):
            result[key] = val[1:-1]
        else:
            result[key] = val
    return result


def shell_timestamp() -> str:
    """Use scripts/now.py canonical source."""
    try:
        out = subprocess.check_output(
            [sys.executable, str(ROOT / "scripts" / "now.py")],
            text=True,
        ).strip()
        return out
    except Exception:
        return _dt.datetime.now().astimezone().isoformat(timespec="seconds")


def load_reports() -> list[tuple[Path, dict]]:
    results: list[tuple[Path, dict]] = []
    if not REPORTS_DIR.exists():
        return results
    for path in sorted(REPORTS_DIR.glob("*.md")):
        if path.name in {"README.md", "INDEX.md"} or path.name.startswith("VIEW-"):
            continue
        text = path.read_text(encoding="utf-8")
        fm = parse_frontmatter(text)
        if fm is None:
            continue
        if fm.get("type") != "report":
            continue
        results.append((path, fm))
    return results


def link(fm: dict) -> str:
    rid = str(fm.get("id", ""))
    return f"[{rid}]({rid}.md)"


def header(title: str, axis: str, count: int, ts: str) -> str:
    return (
        f"# {title}\n\n"
        f"Auto-generated by `scripts/generate_report_views.py`. **Do not edit.**\n\n"
        f"- 집계 축: `{axis}`\n"
        f"- 총 reports: {count}\n"
        f"- 생성 시각: {ts}\n\n"
    )


def render_table(rows: list[tuple[str, list[dict]]]) -> str:
    lines = ["| 키 | 건수 | Reports |", "|----|------|---------|"]
    for key, items in rows:
        ids = ", ".join(link(fm) for fm in items)
        lines.append(f"| {key} | {len(items)} | {ids} |")
    return "\n".join(lines) + "\n"


def by_kind(reports: list[tuple[Path, dict]], ts: str) -> str:
    buckets: dict[str, list[dict]] = defaultdict(list)
    for _, fm in reports:
        kind = str(fm.get("kind", "(unknown)"))
        buckets[kind].append(fm)
    rows = sorted(buckets.items(), key=lambda kv: kv[0])
    return header("Reports by Kind", "kind", len(reports), ts) + render_table(rows)


def by_decision_topic(reports: list[tuple[Path, dict]], ts: str) -> str:
    buckets: dict[str, list[dict]] = defaultdict(list)
    for _, fm in reports:
        topics = fm.get("decision_topics") or []
        if not isinstance(topics, list) or not topics:
            buckets["(none)"].append(fm)
            continue
        for t in topics:
            buckets[str(t)].append(fm)
    rows = sorted(buckets.items(), key=lambda kv: (-len(kv[1]), kv[0]))
    return header("Reports by Decision Topic", "decision_topics[]", len(reports), ts) + render_table(rows)


def by_related_task(reports: list[tuple[Path, dict]], ts: str) -> str:
    buckets: dict[str, list[dict]] = defaultdict(list)
    for _, fm in reports:
        rt = str(fm.get("related_task") or "(none)")
        buckets[rt].append(fm)
    rows = sorted(buckets.items(), key=lambda kv: (-len(kv[1]), kv[0]))
    return header("Reports by Related TASK", "related_task", len(reports), ts) + render_table(rows)


def by_tag(reports: list[tuple[Path, dict]], ts: str) -> str:
    buckets: dict[str, list[dict]] = defaultdict(list)
    for _, fm in reports:
        tags = fm.get("tags") or []
        if not isinstance(tags, list) or not tags:
            buckets["(none)"].append(fm)
            continue
        for t in tags:
            buckets[str(t)].append(fm)
    rows = sorted(buckets.items(), key=lambda kv: (-len(kv[1]), kv[0]))
    return header("Reports by Tag", "tags[]", len(reports), ts) + render_table(rows)


def _strip_volatile(body: str) -> str:
    """Remove lines that change every run (timestamps) so --check can compare stable content."""
    return re.sub(r"^- 생성 시각:.*$", "- 생성 시각: <ignored>", body, flags=re.MULTILINE)


def build_artifacts(ts: str) -> dict[str, str]:
    """Build the 4 VIEW bodies from current reports/. Pure (no disk write)."""
    reports = load_reports()
    return {
        "VIEW-by-kind.md": by_kind(reports, ts),
        "VIEW-by-decision-topic.md": by_decision_topic(reports, ts),
        "VIEW-by-related-task.md": by_related_task(reports, ts),
        "VIEW-by-tag.md": by_tag(reports, ts),
    }


def write_views(quiet: bool = False) -> int:
    """Regenerate all VIEW-*.md from current reports/. Returns report count.

    TASK-148 — callable entry so save_report.py can auto-refresh VIEWs after
    writing a report (COMPOUND-016 CAPA Preventive Action). Used by main() too.
    """
    ts = shell_timestamp()
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    artifacts = build_artifacts(ts)
    for name, body in artifacts.items():
        (REPORTS_DIR / name).write_text(body, encoding="utf-8")
        if not quiet:
            print(f"wrote agents/lead_engineer/reports/{name}")
    reports = load_reports()
    if not quiet:
        print(f"OK: {len(reports)} reports indexed into {len(artifacts)} views")
    return len(reports)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate or check reports/ VIEW-*.md files.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="check disk VIEW-*.md against freshly-generated content; exit 1 if stale.",
    )
    args = parser.parse_args()

    if args.check:
        ts = shell_timestamp()
        reports = load_reports()
        artifacts = build_artifacts(ts)
        stale: list[str] = []
        for name, fresh in artifacts.items():
            path = REPORTS_DIR / name
            if not path.exists():
                stale.append(f"{name} (missing)")
                continue
            on_disk = path.read_text(encoding="utf-8")
            if _strip_volatile(on_disk) != _strip_volatile(fresh):
                stale.append(name)
        if stale:
            print("STALE: " + ", ".join(stale), file=sys.stderr)
            print("Run `python scripts/generate_report_views.py` to refresh.", file=sys.stderr)
            return 1
        print(f"OK: VIEWs up-to-date ({len(reports)} reports / {len(artifacts)} views)")
        return 0

    write_views(quiet=False)
    return 0


if __name__ == "__main__":
    sys.exit(main())
